### ISSUE TITLE
Found solution for HDMI and Battery sensor

### ISSUE THREAD

**Issue by josectheone** [jamieernest/Lenovo-E490-Hackintosh#2]
thanks for your excelente job, after countless hours of trial and error found the correcto kexts and ACPI; feel free to include files of my fork in your repo.

**Comment by jamieernest** [comment]
Right now I do not have access to the laptop as it belongs to my grandparents and I am abroad rn, but I will include it for sure when I get back in 2 months time!

**Comment by lupusellobo** [comment]
I can confirm. Just installed on my e490 and is working flawlessly

**Comment by jamieernest** [comment]
> thanks for your excelente job, after countless hours of trial and error found the correcto kexts and ACPI; feel free to include files of my fork in your repo.

I now have the device with me, can you tell me what you altered to make HDMI work?
(i dont want to just use the EFI and call it a day)

**Comment by josectheone** [comment]
> > thanks for your excelente job, after countless hours of trial and error found the correcto kexts and ACPI; feel free to include files of my fork in your repo.
> 
> I now have the device with me, can you tell me what you altered to make HDMI work?
> (i dont want to just use the EFI and call it a day)

Solution was making the necessary adjustments in this section:

	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>layout-id</key>
				<data>DwAAAA==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,GfxYTile</key>
				<data>AQAAAA==</data>
				<key>AAPL,ig-platform-id</key>
				<data>CQCbPg==</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>device-id</key>
				<data>mz4AAA==</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>disable-external-gpu</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi-dividers-fix</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>enable-lspcon-support</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-con1-busid</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-has-lspcon</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-con1-preferred-lspcon-mode</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-fbmem</key>
				<data>AACQAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
				<key>model</key>
				<string>Intel CoffeeLake-H GT2 [UHD Graphics 630]</string>
			</dict>
		</dict>
		<key>Delete</key>
		<dict/>
	</dict>

**Comment by josectheone** [comment]
Now i have all the kexts updated to the latest version and no issues so far

**Comment by jamieernest** [comment]
I finally got access to the laptop again, and damn it works! Thanks a lot! I'll add it to the next commit :)
Also you seem to have deleted your fork, do you also have the fix for the battery?

**Comment by josectheone** [comment]
> I finally got access to the laptop again, and damn it works! Thanks a lot! I'll add it to the next commit :) Also you seem to have deleted your fork, do you also have the fix for the battery?

Hi add this kext for battery fix
https://github.com/1Revenger1/ECEnabler/releases

**Comment by jamieernest** [comment]
Ah great it works! I'll add both of the patches and I'll definitely thank you for the contributions! Thank you!

**Comment by jamieernest** [comment]
Also I've narrowed the HDMI patch to this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
	<dict>
		<key>AAPL,GfxYTile</key>
		<data>AQAAAA==</data>
		<key>AAPL,ig-platform-id</key>
		<data>CQCbPg==</data>
		<key>device-id</key>
		<data>mz4AAA==</data>
		<key>enable-hdmi-dividers-fix</key>
		<data>AQAAAA==</data>
		<key>enable-hdmi20</key>
		<data>AQAAAA==</data>
		<key>enable-lspcon-support</key>
		<data>AQAAAA==</data>
		<key>framebuffer-con0-enable</key>
		<data>AQAAAA==</data>
		<key>framebuffer-con0-pipe</key>
		<data>EgAAAA==</data>
		<key>framebuffer-con1-busid</key>
		<data>AQAAAA==</data>
		<key>framebuffer-con1-enable</key>
		<data>AQAAAA==</data>
		<key>framebuffer-con1-has-lspcon</key>
		<data>AQAAAA==</data>
		<key>framebuffer-con1-pipe</key>
		<data>EgAAAA==</data>
		<key>framebuffer-con1-preferred-lspcon-mode</key>
		<data>AQAAAA==</data>
		<key>framebuffer-con1-type</key>
		<data>AAgAAA==</data>
		<key>framebuffer-con2-enable</key>
		<data>AQAAAA==</data>
		<key>framebuffer-con2-pipe</key>
		<data>EgAAAA==</data>
		<key>framebuffer-fbmem</key>
		<data>AACQAA==</data>
		<key>framebuffer-patch-enable</key>
		<data>AQAAAA==</data>
		<key>framebuffer-stolenmem</key>
		<data>AAAwAQ==</data>
	</dict>
</dict>
</plist>
```
